---
- name: Start & Enable GlusterFS
  ansible.builtin.systemd:
    name: glusterd
    state: started
    enabled: true

- name: Create directory for GlusterFS volume
  ansible.builtin.file:
    path: /gluster/volume1
    state: directory
    mode: '0755'

- name: Install GlusterFS and create volume  # noqa: no-changed-when
  ansible.builtin.shell: |
    gluster peer probe {{ leader }}
    gluster volume create staging-gfs replica {{ all_nodes | flatten | length }} \
    {{ leader }}:/gluster/volume1 \
    force
    gluster volume start staging-gfs
    chmod 666 /var/run/docker.sock
  delegate_to: "{{ leader }}"
  run_once: true

- name: Ensure GlusterFS mounts on reboot  # noqa: no-changed-when
  ansible.builtin.shell: |
    echo 'localhost:/staging-gfs /mnt glusterfs defaults,_netdev,backupvolfile-server=localhost 0 0' >> /etc/fstab
    mount.glusterfs localhost:/staging-gfs /mnt
    chown -R root:docker /mnt
  with_items: "{{ all_nodes | flatten }}"
  delegate_to: "{{ item }}"
